### ISSUE TITLE
error on scraper

### ISSUE THREAD

**Issue by muhammadanees83** [TomyCesaille/whatsapp-tracking#41]
facing below error while starting docker image... please help

HEADLESS=undefined
scraper_1   | internal/fs/utils.js:230
scraper_1   |     throw err;
scraper_1   |     ^
scraper_1   |
scraper_1   | Error: ENOENT: no such file or directory, open 'no-whatsapp.txt'
scraper_1   |     at Object.openSync (fs.js:458:3)
scraper_1   |     at Object.readFileSync (fs.js:360:35)
scraper_1   |     at Object.<anonymous> (/app/index.js:40:4)
scraper_1   |     at Module._compile (internal/modules/cjs/loader.js:1156:30)
scraper_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
scraper_1   |     at Module.load (internal/modules/cjs/loader.js:1000:32)
scraper_1   |     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
scraper_1   |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
scraper_1   |     at internal/main/run_main_module.js:18:47 {
scraper_1   |   errno: -2,
scraper_1   |   syscall: 'open',
scraper_1   |   code: 'ENOENT',
scraper_1   |   path: 'no-whatsapp.txt'
scraper_1   | }

**Comment by TomyCesaille** [comment]
`master` branch is not that stable! 

One hint: ```Error: ENOENT: no such file or directory, open 'no-whatsapp.txt'```

**Comment by lulu8732** [comment]
> `master` branch is not that stable!
> 
> One hint: `Error: ENOENT: no such file or directory, open 'no-whatsapp.txt'`

Hello @TomyCesaille. Thank you for your stunning  work on this project.

I have the same issue @muhammadanees83 reported.

Could you please tell us where to find (or add) the `no-whatsapp.txt` file. I'm struggling to slove this by myself. 
If the `master` branch is not stable which one do you recommend?

Thanks.

**Comment by TomyCesaille** [comment]
I guess the file just needs to be created by hand before launching to fix.

**Comment by lulu8732** [comment]
I have added the file with 755 permission in the `workspaceFolder` but it's still not recognized. Is there a specific folder to select ?

**Comment by django228** [comment]
any solution?
